/* Generated By:JavaCC: Do not edit this line. DASLTagConstants.java */
package org.exoplatform.services.webdav.search.basicsearch.convertor;

public interface DASLTagConstants {

  int EOF = 0;
  int ALPHA_CHAR = 1;
  int IDENTIFIER_CHAR = 2;
  int QUOTED_STRING = 3;
  int WHITESPACE = 4;
  int NEWLINE = 5;
  int IDENTIFIER_PREFIX = 6;
  int IDENTIFIER = 7;
  int PCData = 8;
  int EOL = 10;
  int OPEN_TAG_BRACKET = 11;
  int OPEN_XML_BRACKET = 12;
  int OPEN_CLOSE_TAG_BRACKET = 13;
  int PCDATA = 14;
  int TAG_NAME = 16;
  int ATTR_NAME = 18;
  int CLOSE_TAG_BRACKET = 19;
  int CLOSE_XML_BRACKET = 20;
  int CLOSE_EMPTY_TAG_BRACKET = 21;
  int ATTR_EQ = 22;
  int ATTR_VAL = 24;

  int LexAttrVal = 0;
  int LexInTag = 1;
  int LexStartTag = 2;
  int DEFAULT = 3;

  String[] tokenImage = {
    "<EOF>",
    "<ALPHA_CHAR>",
    "<IDENTIFIER_CHAR>",
    "<QUOTED_STRING>",
    "<WHITESPACE>",
    "<NEWLINE>",
    "<IDENTIFIER_PREFIX>",
    "<IDENTIFIER>",
    "<PCData>",
    "<token of kind 9>",
    "<EOL>",
    "\"<\"",
    "\"<?\"",
    "\"</\"",
    "<PCDATA>",
    "<token of kind 15>",
    "<TAG_NAME>",
    "<token of kind 17>",
    "<ATTR_NAME>",
    "\">\"",
    "\"?>\"",
    "\"/>\"",
    "\"=\"",
    "<token of kind 23>",
    "<ATTR_VAL>",
  };

}
