/* Generated by Together */

package org.exoplatform.services.jcr.impl.mock;
import org.exoplatform.container.client.ClientInfo;

public class DummyClientInfo implements ClientInfo {

  private String userName;

  public  DummyClientInfo(String userName) {
    this.userName = userName;
  }
  
  public String getClientType() {  return "N/A"; }

  public String getRemoteUser() {  return userName; }

  public String getIpAddress() {  return "N/A"; }

  public String getClientName() {  return "N/A"; }

}
