/* Generated By:JJTree: Do not edit this line. d:/exo/projects/v2.x/exo-jcr/services/jcr/impl/src/java/org/exoplatform/services/jcr/impl/core/query/xpath/\XPathVisitor.java */

package org.exoplatform.services.jcr.impl.core.query.xpath;

public interface XPathVisitor
{
  public Object visit(SimpleNode node, Object data);
}
