/* Generated By:JJTree: Do not edit this line. d:/exo/projects/v2.x/exo-jcr/services/jcr/impl/src/java/org/exoplatform/services/jcr/impl/core/query/lucene/fulltext/\QueryParserTreeConstants.java */

package org.exoplatform.services.jcr.impl.core.query.lucene.fulltext;

public interface QueryParserTreeConstants
{
  public int JJTCONJUNCTION = 0;
  public int JJTMODIFIERS = 1;
  public int JJTQUERY = 2;
  public int JJTCLAUSE = 3;
  public int JJTTERM = 4;


  public String[] jjtNodeName = {
    "Conjunction",
    "Modifiers",
    "Query",
    "Clause",
    "Term",
  };
}
