/* Generated By:JJTree&JavaCC: Do not edit this line. JCRSQLParserConstants.java */
/*
 * Copyright 2004-2005 The Apache Software Foundation or its licensors,
 *                     as applicable.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exoplatform.services.jcr.impl.core.query.sql;

public interface JCRSQLParserConstants {

  int EOF = 0;
  int COMMENT = 5;
  int COMMENT_CHAR = 6;
  int NON_QUOTE_CHAR = 7;
  int COMMENT_INTRO = 8;
  int BY = 9;
  int IN = 10;
  int OR = 11;
  int IS = 12;
  int AND = 13;
  int ASC = 14;
  int NOT = 15;
  int DESC = 16;
  int LIKE = 17;
  int NULL = 18;
  int FROM = 19;
  int ORDER = 20;
  int WHERE = 21;
  int ESCAPE = 22;
  int SELECT = 23;
  int BETWEEN = 24;
  int CONTAINS = 25;
  int SIMPLE_LATIN_LETTER = 26;
  int SIMPLE_LATIN_UPPER_CASE_LETTER = 27;
  int SIMPLE_LATIN_LOWER_CASE_LETTER = 28;
  int LETTER = 29;
  int BASE_CHAR = 30;
  int IDEOGRAPHIC = 31;
  int DIGIT = 32;
  int DOUBLE_QUOTE = 33;
  int PERCENT = 34;
  int AMPERSAND = 35;
  int QUOTE = 36;
  int LEFT_PAREN = 37;
  int RIGHT_PAREN = 38;
  int ASTERISK = 39;
  int PLUS_SIGN = 40;
  int COMMA = 41;
  int MINUS_SIGN = 42;
  int PERIOD = 43;
  int SOLIDUS = 44;
  int COLON = 45;
  int SEMICOLON = 46;
  int LT_OPERATOR = 47;
  int EQ_OPERATOR = 48;
  int GT_OPERATOR = 49;
  int QUESTION_MARK = 50;
  int UNDERSCORE = 51;
  int VERTICAL_BAR = 52;
  int LEFT_BRACKET = 53;
  int RIGHT_BRACKET = 54;
  int REGULAR_IDENTIFIER = 55;
  int IDENTIFIER_BODY = 56;
  int IDENTIFIER_START = 57;
  int IDENTIFIER_PART = 58;
  int DELIMITED_IDENTIFIER = 59;
  int DELIMITED_IDENTIFIER_BODY = 60;
  int DELIMITED_IDENTIFIER_PART = 61;
  int NON_DOUBLE_QUOTE_CHAR = 62;
  int DOUBLE_QUOTE_SYMBOL = 63;
  int NE_OPERATOR = 64;
  int GE_OPERATOR = 65;
  int LE_OPERATOR = 66;
  int CONCAT_OPERATOR = 67;
  int DOUBLE_PERIOD = 68;
  int EXACT_NUMERIC_LITERAL = 69;
  int SIGN = 70;
  int APPROXIMATE_NUMERIC_LITERAL = 71;
  int MANTISSA = 72;
  int EXPONENT = 73;
  int SIGNED_INTEGER = 74;
  int UNSIGNED_INTEGER = 75;
  int DATETIME_LITERAL = 76;
  int DATE_LITERAL = 77;
  int TIMESTAMP_LITERAL = 78;
  int DATE_STRING = 79;
  int TIMESTAMP_STRING = 80;
  int TIME_ZONE_INTERVAL = 81;
  int DATE_VALUE = 82;
  int TIME_VALUE = 83;
  int YEARS_VALUE = 84;
  int MONTHS_VALUE = 85;
  int DAYS_VALUE = 86;
  int HOURS_VALUE = 87;
  int MINUTES_VALUE = 88;
  int SECONDS_VALUE = 89;
  int SECONDS_INTEGER_VALUE = 90;
  int SECONDS_FRACTION = 91;
  int DATETIME_VALUE = 92;
  int CHAR_STRING_LITERAL = 93;
  int CHAR_REPRESENTATION = 94;
  int QUOTE_SYMBOL = 95;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "<COMMENT>",
    "<COMMENT_CHAR>",
    "<NON_QUOTE_CHAR>",
    "<COMMENT_INTRO>",
    "\"BY\"",
    "\"IN\"",
    "\"OR\"",
    "\"IS\"",
    "\"AND\"",
    "\"ASC\"",
    "\"NOT\"",
    "\"DESC\"",
    "\"LIKE\"",
    "\"NULL\"",
    "\"FROM\"",
    "\"ORDER\"",
    "\"WHERE\"",
    "\"ESCAPE\"",
    "\"SELECT\"",
    "\"BETWEEN\"",
    "\"CONTAINS\"",
    "<SIMPLE_LATIN_LETTER>",
    "<SIMPLE_LATIN_UPPER_CASE_LETTER>",
    "<SIMPLE_LATIN_LOWER_CASE_LETTER>",
    "<LETTER>",
    "<BASE_CHAR>",
    "<IDEOGRAPHIC>",
    "<DIGIT>",
    "\"\\\"\"",
    "\"%\"",
    "\"&\"",
    "\"\\\'\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"+\"",
    "\",\"",
    "\"-\"",
    "\".\"",
    "\"/\"",
    "\":\"",
    "\";\"",
    "\"<\"",
    "\"=\"",
    "\">\"",
    "\"?\"",
    "\"_\"",
    "\"|\"",
    "\"[\"",
    "\"]\"",
    "<REGULAR_IDENTIFIER>",
    "<IDENTIFIER_BODY>",
    "<IDENTIFIER_START>",
    "<IDENTIFIER_PART>",
    "<DELIMITED_IDENTIFIER>",
    "<DELIMITED_IDENTIFIER_BODY>",
    "<DELIMITED_IDENTIFIER_PART>",
    "<NON_DOUBLE_QUOTE_CHAR>",
    "<DOUBLE_QUOTE_SYMBOL>",
    "\"<>\"",
    "\">=\"",
    "\"<=\"",
    "\"||\"",
    "\"..\"",
    "<EXACT_NUMERIC_LITERAL>",
    "<SIGN>",
    "<APPROXIMATE_NUMERIC_LITERAL>",
    "<MANTISSA>",
    "<EXPONENT>",
    "<SIGNED_INTEGER>",
    "<UNSIGNED_INTEGER>",
    "<DATETIME_LITERAL>",
    "<DATE_LITERAL>",
    "<TIMESTAMP_LITERAL>",
    "<DATE_STRING>",
    "<TIMESTAMP_STRING>",
    "<TIME_ZONE_INTERVAL>",
    "<DATE_VALUE>",
    "<TIME_VALUE>",
    "<YEARS_VALUE>",
    "<MONTHS_VALUE>",
    "<DAYS_VALUE>",
    "<HOURS_VALUE>",
    "<MINUTES_VALUE>",
    "<SECONDS_VALUE>",
    "<SECONDS_INTEGER_VALUE>",
    "<SECONDS_FRACTION>",
    "<DATETIME_VALUE>",
    "<CHAR_STRING_LITERAL>",
    "<CHAR_REPRESENTATION>",
    "<QUOTE_SYMBOL>",
  };

}
