/* Generated By:JJTree: Do not edit this line. C:\Projects\v2.x\exo-cms\services\jcr\impl\target\generated-src\main\java\org\exoplatform\services\jcr\impl\core\query\sql\JCRSQLParserVisitor.java */

package org.exoplatform.services.jcr.impl.core.query.sql;

public interface JCRSQLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTQuery node, Object data);
  public Object visit(ASTSelectList node, Object data);
  public Object visit(ASTFromClause node, Object data);
  public Object visit(ASTWhereClause node, Object data);
  public Object visit(ASTPredicate node, Object data);
  public Object visit(ASTOrExpression node, Object data);
  public Object visit(ASTAndExpression node, Object data);
  public Object visit(ASTNotExpression node, Object data);
  public Object visit(ASTBracketExpression node, Object data);
  public Object visit(ASTContainsExpression node, Object data);
  public Object visit(ASTLiteral node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTOrderByClause node, Object data);
  public Object visit(ASTOrderSpec node, Object data);
  public Object visit(ASTAscendingOrderSpec node, Object data);
  public Object visit(ASTDescendingOrderSpec node, Object data);
}
