/* Generated By:JJTree: Do not edit this line. C:\Projects\v2.x\exo-cms\services\jcr\impl\target\generated-src\main\java\org\exoplatform\services\jcr\impl\core\query\sql\JCRSQLParserTreeConstants.java */

package org.exoplatform.services.jcr.impl.core.query.sql;

public interface JCRSQLParserTreeConstants
{
  public int JJTQUERY = 0;
  public int JJTSELECTLIST = 1;
  public int JJTVOID = 2;
  public int JJTFROMCLAUSE = 3;
  public int JJTWHERECLAUSE = 4;
  public int JJTPREDICATE = 5;
  public int JJTOREXPRESSION = 6;
  public int JJTANDEXPRESSION = 7;
  public int JJTNOTEXPRESSION = 8;
  public int JJTBRACKETEXPRESSION = 9;
  public int JJTCONTAINSEXPRESSION = 10;
  public int JJTLITERAL = 11;
  public int JJTIDENTIFIER = 12;
  public int JJTORDERBYCLAUSE = 13;
  public int JJTORDERSPEC = 14;
  public int JJTASCENDINGORDERSPEC = 15;
  public int JJTDESCENDINGORDERSPEC = 16;


  public String[] jjtNodeName = {
    "Query",
    "SelectList",
    "void",
    "FromClause",
    "WhereClause",
    "Predicate",
    "OrExpression",
    "AndExpression",
    "NotExpression",
    "BracketExpression",
    "ContainsExpression",
    "Literal",
    "Identifier",
    "OrderByClause",
    "OrderSpec",
    "AscendingOrderSpec",
    "DescendingOrderSpec",
  };
}
